name: "Static code analysis - Lint Check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Lint Check"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: npm run setup
      - name: Run linter
        run: npm run lint
      - run: echo "Completed Lint Check"
